In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

sns.set_context("poster")
sns.set(rc={"figure.figsize": (10.,8.)})
sns.set_style("whitegrid")

In [3]:
train=pd.read_csv('../data/trainclean.csv')

In [4]:
train.head()

,Unnamed: 0,Unnamed: 0.1,ID,Gene,Variation,VariationType,Effect,Class,TEXT,GeneType,Chromosome,Role,TumourType
0,0,0,0,FAM58A,Truncating Mutations,unknown,nonsense,1,cyclin dependent kinases cdks regulate variety...,Unknown,unknown,Unknown,Unknown
1,1,1,1,CBL,W802*,Substitution,nonsense,2,abstract background non small cell lung cancer...,protein-coding,11,"oncogene, TSG, fusion","AML, JMML, MDS"
2,2,2,2,CBL,Q249E,Substitution,missense,2,abstract background non small cell lung cancer...,protein-coding,11,"oncogene, TSG, fusion","AML, JMML, MDS"
3,3,3,3,CBL,N454D,Substitution,missense,3,recent evidence demonstrated acquired uniparen...,protein-coding,11,"oncogene, TSG, fusion","AML, JMML, MDS"
4,4,4,4,CBL,L399V,Substitution,missense,4,oncogenic mutations monomeric casitas b lineag...,protein-coding,11,"oncogene, TSG, fusion","AML, JMML, MDS"

In [5]:
train.drop(columns=['TEXT'], inplace= True)

In [6]:
train.head()

,Unnamed: 0,Unnamed: 0.1,ID,Gene,Variation,VariationType,Effect,Class,GeneType,Chromosome,Role,TumourType
0,0,0,0,FAM58A,Truncating Mutations,unknown,nonsense,1,Unknown,unknown,Unknown,Unknown
1,1,1,1,CBL,W802*,Substitution,nonsense,2,protein-coding,11,"oncogene, TSG, fusion","AML, JMML, MDS"
2,2,2,2,CBL,Q249E,Substitution,missense,2,protein-coding,11,"oncogene, TSG, fusion","AML, JMML, MDS"
3,3,3,3,CBL,N454D,Substitution,missense,3,protein-coding,11,"oncogene, TSG, fusion","AML, JMML, MDS"
4,4,4,4,CBL,L399V,Substitution,missense,4,protein-coding,11,"oncogene, TSG, fusion","AML, JMML, MDS"

In [7]:
train.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'], inplace= True)

In [8]:
train.head()

,ID,Gene,Variation,VariationType,Effect,Class,GeneType,Chromosome,Role,TumourType
0,0,FAM58A,Truncating Mutations,unknown,nonsense,1,Unknown,unknown,Unknown,Unknown
1,1,CBL,W802*,Substitution,nonsense,2,protein-coding,11,"oncogene, TSG, fusion","AML, JMML, MDS"
2,2,CBL,Q249E,Substitution,missense,2,protein-coding,11,"oncogene, TSG, fusion","AML, JMML, MDS"
3,3,CBL,N454D,Substitution,missense,3,protein-coding,11,"oncogene, TSG, fusion","AML, JMML, MDS"
4,4,CBL,L399V,Substitution,missense,4,protein-coding,11,"oncogene, TSG, fusion","AML, JMML, MDS"

In [9]:
train.to_csv('../data/train_no_text.csv')

In [ ]:
enseñar prediccion de resultado